server:
  port: 9002

spring:
  application:
    name: user-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/carbtoon_user?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: wlsdn123

  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: mysql
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        generate_statistics: true
        default_batch_fetch_size: 1000
        format_sql: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

    function:
      definition: carbtoonAuth
    stream:
      kafka:
        bindings:
          carbtoonAuth-out-0:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.StringSerializer
        binder:
          brokers: localhost:9094
      bindings:
        carbtoonAuth-out-0: # (1)
          destination: carbtoon.user # topic
          contentType: application/json

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 604800
    secret: /j7JOK1JQA+cqZhLQF7WVcOzrI0Et0pUZcjhe47ELqQ=

  service:
    username: d245ef53-5ad5-4216-9c56-89fe0f8302a0
    password: ef919ae4-b893-4969-b782-57978180ad33
